"""A fake broker for a zero-latency, limit-order backtest.

Reads the real SPY tick data used elsewhere in Module 7/8
(`scripts/20260401.txt`) and turns each line into an incoming message: either
a quote update (a new best bid/ask) or a trade print. It also holds our own
resting limit orders and, on every trade print, checks whether that trade
would have crossed one of them -- if so it manufactures an OrderFilled message.

"Zero latency" here means our orders/cancels take effect the instant they're
sent, with no simulated wire delay -- not that we can see the future. Only
information from lines already read is ever used.
"""

from dataclasses import dataclass
from datetime import datetime

# ---- market data messages, from the exchange ----


@dataclass
class QuoteUpdate:
    time: datetime
    bid: float
    ask: float


@dataclass
class TradePrint:
    time: datetime
    price: float
    size: int


# ---- broker messages, about our own orders ----


@dataclass
class OrderAccepted:
    order_id: int
    side: str  # "buy" or "sell"


@dataclass
class OrderCanceled:
    order_id: int
    side: str


@dataclass
class OrderFilled:
    order_id: int
    side: str
    price: float
    size: int


def _parse_line(line):
    body = line.strip()
    body = body[len("MarketData(") : -1]
    fields = dict(part.split("=", 1) for part in body.split(", "))
    time = datetime.strptime(fields["time"], "%Y-%m-%d %H:%M:%S.%f")
    if "bid" in fields:
        return QuoteUpdate(time, float(fields["bid"]), float(fields["ask"]))
    return TradePrint(time, float(fields["last"]), int(fields["size"]))


class FakeBroker:
    """Plays back one ticker's real quote/trade tape and matches our resting limit orders."""

    def __init__(self, data_path):
        self._file = open(data_path)
        self._resting = {}  # side -> (order_id, price, size)
        self._next_order_id = 1
        self._pending_broker_messages = []
        self.done = False

    def send_limit_order(self, side, price, size):
        """Place (replacing any existing) resting limit order on `side` ("buy"/"sell")."""
        order_id = self._next_order_id
        self._next_order_id += 1
        self._resting[side] = (order_id, price, size)
        self._pending_broker_messages.append(OrderAccepted(order_id, side))

    def cancel_order(self, side):
        """Cancel our resting order on `side`, if any."""
        resting = self._resting.pop(side, None)
        if resting is not None:
            self._pending_broker_messages.append(OrderCanceled(resting[0], side))

    def poll(self):
        """Read the next tape line and return the list of messages it produces.

        Always starts with any broker messages (accepts/cancels) generated by
        orders sent since the last call, followed by the market data message
        itself, followed by an OrderFilled if that trade crossed one of our
        resting orders. Returns an empty list once the tape is exhausted
        (check `.done`).
        """
        line = self._file.readline()
        if not line:
            self.done = True
            return []

        messages = self._pending_broker_messages
        self._pending_broker_messages = []

        event = _parse_line(line)
        messages.append(event)

        if isinstance(event, TradePrint):
            messages.extend(self._check_fill(event))

        return messages

    def _check_fill(self, trade):
        fills = []
        buy = self._resting.get("buy")
        if buy is not None and trade.price <= buy[1]:
            fills.append(OrderFilled(buy[0], "buy", buy[1], min(buy[2], trade.size)))
            del self._resting["buy"]
        sell = self._resting.get("sell")
        if sell is not None and trade.price >= sell[1]:
            fills.append(OrderFilled(sell[0], "sell", sell[1], min(sell[2], trade.size)))
            del self._resting["sell"]
        return fills

    def close(self):
        self._file.close()
